name: CI - Workflow
on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
env:
  PYTHON_VERSION: "3.12"
  POETRY_VERSION: "1.7.1"
  PYLINT_THRESHOLD: "3"
jobs:
  install-test-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Create Project Folder environment variable
        run: echo "PROJECT_FOLDER=$(echo "${{ github.event.repository.name }}" | sed -e 's/package-python-//' -e 's/-/_/g')" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup python versions
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.3.0
        with:
          poetry-version: ${{ env.POETRY_VERSION }}
      - name: Install Python dependencies
        run: poetry install
      - name: Code quality
        run: poetry run pylint --fail-under=${{ env.PYLINT_THRESHOLD }} **/*py
      - name: Test & Generate Coverage Report
        run: |
          poetry run coverage run --source ${{ env.PROJECT_FOLDER }}/ -m pytest --junitxml=pytest.xml
          poetry run coverage xml
  publish-in-pypi:
    runs-on: ubuntu-latest
    needs: [install-test-coverage]
    if: contains(github.event_commit.message, 'publish')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup python versions
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.3.0
        with:
          poetry-version: ${{ env.POETRY_VERSION }}
      - name: Pypi Publish
        run: poetry publish --build
        env: 
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.POETRY_PYPI_TOKEN_PYPI }}
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    needs: [install-test-coverage]
    if: contains(github.event_commit.message, 'publish')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup python versions
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.3.0
        with:
          poetry-version: ${{ env.POETRY_VERSION }}
      - name: Set version
        run: |
          echo "PACKAGE_VERSION=$(poetry version --no-ansi | cut -d ' ' -f 2)" >> $GITHUB_ENV
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU 
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-